"""fix field error context to content

Revision ID: 38cd7c2587b0
Revises: 144d7bc0cb7c
Create Date: 2026-09-01 14:55:46.722176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cd7c2587b0'
down_revision: Union[str, Sequence[str], None] = '144d7bc0cb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('document_chunks', 'context')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('context', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('document_chunks', 'content')
    # ### end Alembic commands ###
